project:
  type: website

website:
  title: "Michael Schuhler"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - text: Projects
      - text: Resume/CV
    right:
      - text: Contact Me

format:
  html:
    theme: cosmo
    css: styles.css
