project:
  type: website

format:
  html:
    theme: lux
    css: styles.css

website:
  title: "Michael Schuhler"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume/CV
    right:
      - href: contact.qmd
        text: Contact Me


